sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t learning/docker-react .

script:
  - docker run -e CI=true learning/docker-react npm run test

